name: Node CI

on: [push, pull_request]

jobs:
  lint:
    name: Run tslint on node ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # node-version: [10.x, 12.x]
        node-version: [12.x, 18.0.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, prepublish, and lint
      run: |
        npm install
        npm run vscode:prepublish
        npm run tslint
